/*Copyright (c) 2019-2020 voyy.com All Rights Reserved.
 This software is the confidential and proprietary information of voyy.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with voyy.com*/
package com.rapido.deodongskokvdk.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class BrandsResponse implements Serializable {


    @ColumnAlias("Item Name")
    private String itemName;

    @ColumnAlias("UPC")
    private String upc;

    @ColumnAlias("Brand Name")
    private String brandName;

    public String getItemName() {
        return this.itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getUpc() {
        return this.upc;
    }

    public void setUpc(String upc) {
        this.upc = upc;
    }

    public String getBrandName() {
        return this.brandName;
    }

    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof BrandsResponse)) return false;
        final BrandsResponse brandsResponse = (BrandsResponse) o;
        return Objects.equals(getItemName(), brandsResponse.getItemName()) &&
                Objects.equals(getUpc(), brandsResponse.getUpc()) &&
                Objects.equals(getBrandName(), brandsResponse.getBrandName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getItemName(),
                getUpc(),
                getBrandName());
    }
}