/*Copyright (c) 2019-2020 voyy.com All Rights Reserved.
 This software is the confidential and proprietary information of voyy.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with voyy.com*/
package com.rapido.deodongskokvdk.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class RapidoResponse implements Serializable {


    @ColumnAlias("accountsource")
    private String accountsource;

    @ColumnAlias("name")
    private String name;

    @ColumnAlias("isdeleted")
    private Boolean isdeleted;

    @ColumnAlias("systemmodstamp")
    private Timestamp systemmodstamp;

    @ColumnAlias("createddate")
    private Timestamp createddate;

    @ColumnAlias("accountnumber")
    private String accountnumber;

    @ColumnAlias("annualrevenue")
    private BigDecimal annualrevenue;

    @ColumnAlias("active__c")
    private String activeC;

    @ColumnAlias("sfid")
    private String sfid;

    @ColumnAlias("id")
    private Integer id;

    @ColumnAlias("_hc_lastop")
    private String hcLastop;

    @ColumnAlias("_hc_err")
    private String hcErr;

    @ColumnAlias("numberofemployees")
    private Integer numberofemployees;

    @ColumnAlias("account_ext_id__c")
    private String accountExtIdC;

    @ColumnAlias("billingcity")
    private String billingcity;

    @ColumnAlias("type")
    private String type;

    @ColumnAlias("billingcountry")
    private String billingcountry;

    public String getAccountsource() {
        return this.accountsource;
    }

    public void setAccountsource(String accountsource) {
        this.accountsource = accountsource;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getIsdeleted() {
        return this.isdeleted;
    }

    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    public Timestamp getSystemmodstamp() {
        return this.systemmodstamp;
    }

    public void setSystemmodstamp(Timestamp systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    public Timestamp getCreateddate() {
        return this.createddate;
    }

    public void setCreateddate(Timestamp createddate) {
        this.createddate = createddate;
    }

    public String getAccountnumber() {
        return this.accountnumber;
    }

    public void setAccountnumber(String accountnumber) {
        this.accountnumber = accountnumber;
    }

    public BigDecimal getAnnualrevenue() {
        return this.annualrevenue;
    }

    public void setAnnualrevenue(BigDecimal annualrevenue) {
        this.annualrevenue = annualrevenue;
    }

    public String getActiveC() {
        return this.activeC;
    }

    public void setActiveC(String activeC) {
        this.activeC = activeC;
    }

    public String getSfid() {
        return this.sfid;
    }

    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getHcLastop() {
        return this.hcLastop;
    }

    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    public String getHcErr() {
        return this.hcErr;
    }

    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }

    public Integer getNumberofemployees() {
        return this.numberofemployees;
    }

    public void setNumberofemployees(Integer numberofemployees) {
        this.numberofemployees = numberofemployees;
    }

    public String getAccountExtIdC() {
        return this.accountExtIdC;
    }

    public void setAccountExtIdC(String accountExtIdC) {
        this.accountExtIdC = accountExtIdC;
    }

    public String getBillingcity() {
        return this.billingcity;
    }

    public void setBillingcity(String billingcity) {
        this.billingcity = billingcity;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getBillingcountry() {
        return this.billingcountry;
    }

    public void setBillingcountry(String billingcountry) {
        this.billingcountry = billingcountry;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RapidoResponse)) return false;
        final RapidoResponse rapidoResponse = (RapidoResponse) o;
        return Objects.equals(getAccountsource(), rapidoResponse.getAccountsource()) &&
                Objects.equals(getName(), rapidoResponse.getName()) &&
                Objects.equals(getIsdeleted(), rapidoResponse.getIsdeleted()) &&
                Objects.equals(getSystemmodstamp(), rapidoResponse.getSystemmodstamp()) &&
                Objects.equals(getCreateddate(), rapidoResponse.getCreateddate()) &&
                Objects.equals(getAccountnumber(), rapidoResponse.getAccountnumber()) &&
                Objects.equals(getAnnualrevenue(), rapidoResponse.getAnnualrevenue()) &&
                Objects.equals(getActiveC(), rapidoResponse.getActiveC()) &&
                Objects.equals(getSfid(), rapidoResponse.getSfid()) &&
                Objects.equals(getId(), rapidoResponse.getId()) &&
                Objects.equals(getHcLastop(), rapidoResponse.getHcLastop()) &&
                Objects.equals(getHcErr(), rapidoResponse.getHcErr()) &&
                Objects.equals(getNumberofemployees(), rapidoResponse.getNumberofemployees()) &&
                Objects.equals(getAccountExtIdC(), rapidoResponse.getAccountExtIdC()) &&
                Objects.equals(getBillingcity(), rapidoResponse.getBillingcity()) &&
                Objects.equals(getType(), rapidoResponse.getType()) &&
                Objects.equals(getBillingcountry(), rapidoResponse.getBillingcountry());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAccountsource(),
                getName(),
                getIsdeleted(),
                getSystemmodstamp(),
                getCreateddate(),
                getAccountnumber(),
                getAnnualrevenue(),
                getActiveC(),
                getSfid(),
                getId(),
                getHcLastop(),
                getHcErr(),
                getNumberofemployees(),
                getAccountExtIdC(),
                getBillingcity(),
                getType(),
                getBillingcountry());
    }
}