/*Copyright (c) 2019-2020 voyy.com All Rights Reserved.
 This software is the confidential and proprietary information of voyy.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with voyy.com*/
package com.rapido.deodongskokvdk;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * GroceryBrandC generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`grocery_brand__c`")
public class GroceryBrandC implements Serializable {

    private Integer id;
    private LocalDateTime createddate;
    private Boolean isdeleted;
    private String name;
    private LocalDateTime systemmodstamp;
    private String groceryBrandExtIdC;
    private String brandWebSiteC;
    private String sfid;
    private String hcLastop;
    private String hcErr;

    @Id
    @SequenceGenerator(name = "generator", sequenceName = "`grocery_brand__c_id_seq`" , allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`createddate`", nullable = true)
    public LocalDateTime getCreateddate() {
        return this.createddate;
    }

    public void setCreateddate(LocalDateTime createddate) {
        this.createddate = createddate;
    }

    @Column(name = "`isdeleted`", nullable = true)
    public Boolean getIsdeleted() {
        return this.isdeleted;
    }

    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    @Column(name = "`name`", nullable = true, length = 80)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "`systemmodstamp`", nullable = true)
    public LocalDateTime getSystemmodstamp() {
        return this.systemmodstamp;
    }

    public void setSystemmodstamp(LocalDateTime systemmodstamp) {
        this.systemmodstamp = systemmodstamp;
    }

    @Column(name = "`grocery_brand_ext_id__c`", nullable = true, length = 25)
    public String getGroceryBrandExtIdC() {
        return this.groceryBrandExtIdC;
    }

    public void setGroceryBrandExtIdC(String groceryBrandExtIdC) {
        this.groceryBrandExtIdC = groceryBrandExtIdC;
    }

    @Column(name = "`brand_web_site__c`", nullable = true, length = 255)
    public String getBrandWebSiteC() {
        return this.brandWebSiteC;
    }

    public void setBrandWebSiteC(String brandWebSiteC) {
        this.brandWebSiteC = brandWebSiteC;
    }

    @Column(name = "`sfid`", nullable = true, length = 18)
    public String getSfid() {
        return this.sfid;
    }

    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    @Column(name = "`_hc_lastop`", nullable = true, length = 32)
    public String getHcLastop() {
        return this.hcLastop;
    }

    public void setHcLastop(String hcLastop) {
        this.hcLastop = hcLastop;
    }

    @Column(name = "`_hc_err`", nullable = true, length = 2147483647)
    public String getHcErr() {
        return this.hcErr;
    }

    public void setHcErr(String hcErr) {
        this.hcErr = hcErr;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GroceryBrandC)) return false;
        final GroceryBrandC groceryBrandC = (GroceryBrandC) o;
        return Objects.equals(getId(), groceryBrandC.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}