/*Copyright (c) 2019-2020 voyy.com All Rights Reserved.
 This software is the confidential and proprietary information of voyy.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with voyy.com*/
package com.rapido.deodongskokvdk.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.rapido.deodongskokvdk.models.query.*;

public interface DeodongskokvdkQueryExecutorService {

    Page<BrandsResponse> executeBrands(Pageable pageable);

    void exportBrands(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<RapidoAccountResponse> executeRapidoAccount(Pageable pageable);

    void exportRapidoAccount(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<RapidoResponse> executeRapido(Pageable pageable);

    void exportRapido(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}